### ISSUE TITLE
x-powered header set by speed booster pack

### ISSUE THREAD

**Issue by n82freak** [optimocha/speed-booster-pack#69]
hi. I try to hide the x-powered header by php.ini and htaccess but speed booster pack plugin always show the x-powered header. 
Is there any option to hide that?

**Comment by optimocha** [comment]
Hi @n82freak,

I assume you tried to use the following php.ini directive:

`expose_php = Off`

If that doesn't work even after restarting your server, and you're using PHP version 7.0 or above, you can try adding the following to your .htaccess file:

```
Header always unset X-Powered-By
Header unset X-Powered-By
```

**Comment by n82freak** [comment]
Hi. I tried with both options.

In htaccess with Header unset X-Powered-By
Not working

Then i tried Header always unset X-Powered-By
Not working

Then i tried with php.ini with expose_php = Off
Not working

My SEO Tool tell me that the x-powered header is explizit set by speed
booster pack.

In attachments i can give you the header output.

I have no idea and the support from my hoster also have no idea.
Thats why i ask you!

Greetz

Optimocha ***@***.***> schrieb am Fr., 21. Juli 2023, 20:23:

**Comment by optimocha** [comment]
Thank you @n82freak! If none of them works, it might be a misconfiguration of caching layers on top of WordPress. It's also possible that your php.ini or .htaccess configurations are not going into effect because there's some higher-level configuration that overrides your configs. Speed Booster Pack (or any other plugin for that matter) can't possibly override any server configuration so I'm 100% sure that you can't resolve this issue on the WordPress level.

Moreover, the code of our plugin's latest version doesn't have any HTTP headers pushed (check [speed-booster-pack/includes/class-speed-booster-pack.php, line 284](https://github.com/optimocha/speed-booster-pack/blob/main/includes/class-speed-booster-pack.php#L284)). Thus, updating SBP to the latest version (4.5.6) is the easiest way to resolve your issue.

**Comment by n82freak** [comment]
Here you can see that the x-powered header is set by speed booster pack.
Not by any other plugin or something.
My Hoster tell me that all configs are good and the x-powered header is
defenitly set by speed booster pack.

Optimocha ***@***.***> schrieb am Di., 25. Juli 2023, 15:48:

**Comment by optimocha** [comment]
@n82freak can you tell me which version of Speed Booster Pack you're using?

**Comment by n82freak** [comment]
Line 284:  // $this->loader->add_filter( 'wp_headers', $plugin_public, 'sbp_headers' );
